/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.proway.protify.telas;

import br.com.proway.protify.dao.ArtistaDAO;
import br.com.proway.protify.modelo.Artista;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Francisco Aulas
 */
public class ArtistasJFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ArtistasJFrame.class.getName());

    private int idParaEditar = -1;

    /**
     * Creates new form ArtistasJFrame
     */
    public ArtistasJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTrabalhando = new javax.swing.ButtonGroup();
        buttonGroupOperacao = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAnoEstreia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonTrabalhandoSim = new javax.swing.JRadioButton();
        jRadioButtonTrabalhandoNao = new javax.swing.JRadioButton();
        jComboBoxPais = new javax.swing.JComboBox<>();
        jButtonAtualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaArtistas = new javax.swing.JTextArea();
        jButtonApagar = new javax.swing.JButton();
        jLabelIdParaEditar = new javax.swing.JLabel();
        jTextFieldIdApagar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonOperacaoCadastrar = new javax.swing.JRadioButton();
        jRadioButtonOperacaoEditar = new javax.swing.JRadioButton();
        jComboBoxArtistasParaEditar = new javax.swing.JComboBox<>();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Nome");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(this::jButtonSalvarActionPerformed);

        jLabel2.setText("Pais");

        jLabel3.setText("Ano Estreia");

        jLabel4.setText("Trabalhando?");

        buttonGroupTrabalhando.add(jRadioButtonTrabalhandoSim);
        jRadioButtonTrabalhandoSim.setText("Sim");

        buttonGroupTrabalhando.add(jRadioButtonTrabalhandoNao);
        jRadioButtonTrabalhandoNao.setText("Não");

        jComboBoxPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BR", "US", "CA" }));
        jComboBoxPais.setSelectedIndex(-1);

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(this::jButtonAtualizarActionPerformed);

        jLabel5.setText("Artistas");

        jTextAreaArtistas.setColumns(20);
        jTextAreaArtistas.setRows(5);
        jScrollPane1.setViewportView(jTextAreaArtistas);

        jButtonApagar.setText("Apagar");
        jButtonApagar.addActionListener(this::jButtonApagarActionPerformed);

        jLabelIdParaEditar.setText("Artista");
        jLabelIdParaEditar.setEnabled(false);

        jLabel7.setText("ID");

        buttonGroupOperacao.add(jRadioButtonOperacaoCadastrar);
        jRadioButtonOperacaoCadastrar.setSelected(true);
        jRadioButtonOperacaoCadastrar.setText("Cadastrar");
        jRadioButtonOperacaoCadastrar.addActionListener(this::jRadioButtonOperacaoCadastrarActionPerformed);

        buttonGroupOperacao.add(jRadioButtonOperacaoEditar);
        jRadioButtonOperacaoEditar.setText("Editar");
        jRadioButtonOperacaoEditar.addActionListener(this::jRadioButtonOperacaoEditarActionPerformed);

        jComboBoxArtistasParaEditar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxArtistasParaEditar.setSelectedIndex(-1);
        jComboBoxArtistasParaEditar.setEnabled(false);
        jComboBoxArtistasParaEditar.addActionListener(this::jComboBoxArtistasParaEditarActionPerformed);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(this::jButtonCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(31, 31, 31)
                        .addComponent(jTextFieldIdApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonApagar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelIdParaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSalvar)
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonTrabalhandoSim, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonTrabalhandoNao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonOperacaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonOperacaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBoxArtistasParaEditar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxPais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldAnoEstreia)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAtualizar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAtualizar)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonOperacaoCadastrar)
                            .addComponent(jRadioButtonOperacaoEditar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxArtistasParaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelIdParaEditar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAnoEstreia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButtonTrabalhandoSim)
                                    .addComponent(jRadioButtonTrabalhandoNao)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4)))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSalvar)
                            .addComponent(jButtonCancelar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIdApagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonApagar)
                            .addComponent(jLabel7))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        String nome = jTextFieldNome.getText();
        // Pegar o pais selecionado do combo box
        String pais = jComboBoxPais.getSelectedItem().toString();
        int anoEstreia = Integer.parseInt(jTextFieldAnoEstreia.getText());
        boolean trabalhando = jRadioButtonTrabalhandoSim.isSelected();

        Artista artista = new Artista();
        artista.setNome(nome);
        artista.setPais(pais);
        artista.setAnoEstreia(anoEstreia);
        artista.setTrabalhando(trabalhando);

        if (idParaEditar == -1) {
            cadastrar(artista);
        } else {
            artista.setId(idParaEditar);
            editar(artista);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        carregarArtistas();
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        int id = Integer.parseInt(jTextFieldIdApagar.getText());
        try {
            ArtistaDAO dao = new ArtistaDAO();
            dao.delete(id);
            JOptionPane.showMessageDialog(null, "Artista apagado com sucesso");
            jTextFieldIdApagar.setText("");
            carregarArtistas();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao apagar");
        }
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jRadioButtonOperacaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOperacaoEditarActionPerformed
        jComboBoxArtistasParaEditar.setEnabled(true);
        jLabelIdParaEditar.setEnabled(true);

        carregarComboBoxParaEditar();
    }//GEN-LAST:event_jRadioButtonOperacaoEditarActionPerformed

    private void jRadioButtonOperacaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOperacaoCadastrarActionPerformed
        jComboBoxArtistasParaEditar.setEnabled(false);
        jLabelIdParaEditar.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonOperacaoCadastrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carregarArtistas();
    }//GEN-LAST:event_formWindowOpened

    private void jComboBoxArtistasParaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxArtistasParaEditarActionPerformed
        if (jComboBoxArtistasParaEditar.getSelectedIndex() == -1) {
            return;
        }

        Artista artista = (Artista) jComboBoxArtistasParaEditar.getSelectedItem();

        idParaEditar = artista.getId();

        jTextFieldNome.setText(artista.getNome());
        jComboBoxPais.setSelectedItem(artista.getPais());
        jTextFieldAnoEstreia.setText(String.valueOf(artista.getAnoEstreia()));
        if (artista.isTrabalhando()) {
            jRadioButtonTrabalhandoSim.setSelected(true);
        } else {
            jRadioButtonTrabalhandoNao.setSelected(true);
        }
    }//GEN-LAST:event_jComboBoxArtistasParaEditarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void editar(Artista artista) {
        try {
            ArtistaDAO dao = new ArtistaDAO();
            dao.editar(artista);
            JOptionPane.showMessageDialog(null, "Artista alterado com sucesso");
            limparCampos();
            carregarArtistas();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao alterar");
        }
    }

    private void cadastrar(Artista artista) {
        try {
            ArtistaDAO dao = new ArtistaDAO();
            dao.inserir(artista);
            JOptionPane.showMessageDialog(null, "Artista cadastrado com sucesso");
            limparCampos();
            carregarArtistas();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao cadastrar");
        }
    }

    private void carregarArtistas() {
        try {
            ArtistaDAO dao = new ArtistaDAO();
            ArrayList<Artista> artistas = dao.consultarTodos();
            String resultados = "";
            for (int i = 0; i < artistas.size(); i++) {
                Artista artista = artistas.get(i);

                resultados += "Artista: " + artista.getNome()
                        + "\nCódigo: " + artista.getId()
                        + "\nPais: " + artista.getPais()
                        + "\nAno de Estreia: " + artista.getAnoEstreia()
                        + "\nTrabalhando: " + artista.isTrabalhando()
                        + "\n----------------------------------------------------\n";
            }
            jTextAreaArtistas.setText(resultados);
            jTextAreaArtistas.setCaretPosition(0);
            jTextFieldNome.requestFocus();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao listar");
        }
    }

    private void limparCampos() {
        jTextFieldNome.setText("");
        jComboBoxPais.setSelectedIndex(-1);
        jTextFieldAnoEstreia.setText("");
        buttonGroupTrabalhando.clearSelection();
        jComboBoxArtistasParaEditar.setSelectedIndex(-1);
        jRadioButtonOperacaoCadastrar.setSelected(true);
        jLabelIdParaEditar.setEnabled(false);
        jComboBoxArtistasParaEditar.setEnabled(false);
        idParaEditar = -1;
    }

    private void carregarComboBoxParaEditar() {
        ArtistaDAO dao = new ArtistaDAO();
        try {
            ArrayList<Artista> artistas = dao.consultarTodos();

            DefaultComboBoxModel itensComboBox = new DefaultComboBoxModel();
            // Remover
            itensComboBox.removeAllElements();

            for (int i = 0; i < artistas.size(); i++) {
                Artista artista = artistas.get(i);
                itensComboBox.addElement(artista);
            }

            jComboBoxArtistasParaEditar.setModel(itensComboBox);
            jComboBoxArtistasParaEditar.setSelectedIndex(-1);

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao listar");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ArtistasJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupOperacao;
    private javax.swing.ButtonGroup buttonGroupTrabalhando;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxArtistasParaEditar;
    private javax.swing.JComboBox<String> jComboBoxPais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelIdParaEditar;
    private javax.swing.JRadioButton jRadioButtonOperacaoCadastrar;
    private javax.swing.JRadioButton jRadioButtonOperacaoEditar;
    private javax.swing.JRadioButton jRadioButtonTrabalhandoNao;
    private javax.swing.JRadioButton jRadioButtonTrabalhandoSim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaArtistas;
    private javax.swing.JTextField jTextFieldAnoEstreia;
    private javax.swing.JTextField jTextFieldIdApagar;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
